-- Phase 5.1: seed reusable starter jobs and activities using the existing data model.
-- This keeps the foundation data-driven and safe to re-run without duplicating rows.

insert into public.jobs (
  slug,
  name,
  description,
  salary,
  energy_cost,
  required_level,
  cooldown_minutes,
  xp_reward,
  stat_bonus,
  icon,
  sort_order,
  category,
  duration_minutes,
  hunger_cost,
  thirst_cost,
  reputation_reward,
  requirements,
  metadata,
  location_id,
  place_id,
  is_available
)
values
  (
    'junior_frontend_developer',
    'Junior Frontend Developer',
    'Build pages, fix frontend bugs, and support a small digital team.',
    8000,
    15,
    2,
    30,
    50,
    'intelligence',
    'code',
    80,
    'technology',
    30,
    5,
    4,
    2,
    '{"level":2,"skills":[{"slug":"javascript","minimum_level":20}]}'::jsonb,
    '{"team":"tech","area":"digital"}'::jsonb,
    (select id from public.locations where slug = 'student-district'),
    null,
    true
  ),
  (
    'barber_assistant_osogbo',
    'Barber Assistant',
    'Assist the barber with prep, cleanup, and customer service.',
    4000,
    18,
    1,
    12,
    32,
    'social',
    'scissors',
    81,
    'services',
    45,
    6,
    4,
    1,
    '{"level":1}'::jsonb,
    '{"team":"service","area":"salon"}'::jsonb,
    (select id from public.locations where slug = 'oke-fia'),
    null,
    true
  ),
  (
    'market_trader',
    'Market Trader',
    'Manage a small stall, help customers, and move goods around the market.',
    5500,
    20,
    1,
    15,
    38,
    'social',
    'store',
    82,
    'trading',
    40,
    7,
    5,
    2,
    '{"level":1,"skills":[{"slug":"trading","minimum_level":10}]}'::jsonb,
    '{"team":"retail","area":"market"}'::jsonb,
    (select id from public.locations where slug = 'oja-oba'),
    null,
    true
  ),
  (
    'restaurant_worker',
    'Restaurant Worker',
    'Take orders, clear tables, and keep the kitchen line moving.',
    5200,
    18,
    1,
    15,
    35,
    'social',
    'utensils',
    83,
    'food_hospitality',
    35,
    7,
    5,
    2,
    '{"level":1}'::jsonb,
    '{"team":"hospitality","area":"restaurant"}'::jsonb,
    (select id from public.locations where slug = 'oke-fia'),
    null,
    true
  ),
  (
    'driver_rider',
    'Driver',
    'Move passengers and goods between busy halls of the city.',
    6000,
    20,
    1,
    20,
    36,
    'reputation',
    'bike',
    84,
    'transportation',
    30,
    5,
    5,
    2,
    '{"level":1,"skills":[{"slug":"driving","minimum_level":10}]}'::jsonb,
    '{"team":"transport","area":"garage"}'::jsonb,
    (select id from public.locations where slug = 'old-garage'),
    null,
    true
  ),
  (
    'mechanic_assistant',
    'Mechanic Assistant',
    'Support parts lookup, cleanup, and small repairs in a busy workshop.',
    6800,
    20,
    2,
    20,
    42,
    'career',
    'wrench',
    85,
    'construction',
    50,
    8,
    5,
    2,
    '{"level":2,"skills":[{"slug":"mechanics","minimum_level":15}]}'::jsonb,
    '{"team":"workshop","area":"garage"}'::jsonb,
    (select id from public.locations where slug = 'old-garage'),
    null,
    true
  )
on conflict (slug)
do update set
  name = excluded.name,
  description = excluded.description,
  salary = excluded.salary,
  energy_cost = excluded.energy_cost,
  required_level = excluded.required_level,
  cooldown_minutes = excluded.cooldown_minutes,
  xp_reward = excluded.xp_reward,
  stat_bonus = excluded.stat_bonus,
  icon = excluded.icon,
  sort_order = excluded.sort_order,
  category = excluded.category,
  duration_minutes = excluded.duration_minutes,
  hunger_cost = excluded.hunger_cost,
  thirst_cost = excluded.thirst_cost,
  reputation_reward = excluded.reputation_reward,
  requirements = excluded.requirements,
  metadata = excluded.metadata,
  location_id = excluded.location_id,
  place_id = excluded.place_id,
  is_available = excluded.is_available;

insert into public.activities (
  slug,
  name,
  category,
  description,
  location_id,
  duration_minutes,
  energy_delta,
  hunger_delta,
  thirst_delta,
  xp_reward,
  requirements,
  rewards,
  cooldown_minutes,
  is_available,
  metadata
)
values
  (
    'rest',
    'Rest',
    'rest',
    'Take a breather and recover energy after a busy day.',
    null,
    30,
    25,
    3,
    2,
    4,
    '{"type":"none"}'::jsonb,
    '{"energy":25}'::jsonb,
    0,
    true,
    '{"restorative":true}'::jsonb
  ),
  (
    'study',
    'Study',
    'study',
    'Read, practice, and improve your mind with a focused study session.',
    (select id from public.locations where slug = 'student-district'),
    30,
    -8,
    4,
    4,
    12,
    '{"type":"none"}'::jsonb,
    '{"skillXp":"study"}'::jsonb,
    15,
    true,
    '{"skill":"learning"}'::jsonb
  ),
  (
    'exercise',
    'Exercise',
    'exercise',
    'Train your body and build stamina in a short workout.',
    (select id from public.locations where slug = 'oke-fia'),
    30,
    -10,
    5,
    6,
    10,
    '{"type":"none"}'::jsonb,
    '{"skillXp":"fitness"}'::jsonb,
    15,
    true,
    '{"skill":"fitness"}'::jsonb
  ),
  (
    'socialize',
    'Socialize',
    'social',
    'Chat with people, network, and build local ties in the city.',
    null,
    30,
    -5,
    3,
    4,
    8,
    '{"type":"none"}'::jsonb,
    '{"social":1}'::jsonb,
    20,
    true,
    '{"skill":"social"}'::jsonb
  ),
  (
    'explore_city',
    'Explore the city',
    'exploration',
    'Wander a new part of Osogbo and learn more about the world.',
    null,
    25,
    -6,
    3,
    4,
    8,
    '{"type":"none"}'::jsonb,
    '{"discovery":true}'::jsonb,
    30,
    true,
    '{"discovery":true}'::jsonb
  ),
  (
    'eat_meal',
    'Eat a meal',
    'food',
    'Take a short break to eat and restore stamina.',
    null,
    20,
    8,
    -25,
    0,
    3,
    '{"type":"none"}'::jsonb,
    '{"hunger":-25}'::jsonb,
    10,
    true,
    '{"restorative":true}'::jsonb
  )
on conflict (slug)
do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  location_id = excluded.location_id,
  duration_minutes = excluded.duration_minutes,
  energy_delta = excluded.energy_delta,
  hunger_delta = excluded.hunger_delta,
  thirst_delta = excluded.thirst_delta,
  xp_reward = excluded.xp_reward,
  requirements = excluded.requirements,
  rewards = excluded.rewards,
  cooldown_minutes = excluded.cooldown_minutes,
  is_available = excluded.is_available,
  metadata = excluded.metadata;
